export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  UNKNOWN = 'UNKNOWN'
}

export enum RecoveryStatus {
  DETECTED = 'DETECTED',
  DIAGNOSING = 'DIAGNOSING',
  PLANNED = 'PLANNED',
  POLICY_CHECK = 'POLICY_CHECK',
  READY = 'READY',
  EXECUTING = 'EXECUTING',
  VERIFYING = 'VERIFYING',
  PROMISE_TO_PAY = 'PROMISE_TO_PAY',
  RECOVERED = 'RECOVERED',
  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  ESCALATED = 'ESCALATED',
  STOPPED = 'STOPPED',
  FAILED = 'FAILED'
}

export enum FailureCategory {
  TRANSIENT = 'TRANSIENT',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  BANK_FAILURE = 'BANK_FAILURE',
  NETWORK_FAILURE = 'NETWORK_FAILURE',
  ABANDONMENT = 'ABANDONMENT',
  UNKNOWN = 'UNKNOWN'
}

export enum RecoveryActionType {
  IMMEDIATE_RETRY = 'IMMEDIATE_RETRY',
  DELAYED_RETRY = 'DELAYED_RETRY',
  REMINDER = 'REMINDER',
  SCHEDULE_PROMISE = 'SCHEDULE_PROMISE',
  ESCALATE = 'ESCALATE'
}

export enum CustomerIntent {
  PAY_LATER = 'PAY_LATER',
  READY_NOW = 'READY_NOW',
  CANCEL_ORDER = 'CANCEL_ORDER',
  DISPUTE = 'DISPUTE'
}
